#!/usr/bin/perl -w 
use strict ;
use FileHandle ;
use Getopt::Long;
use Cwd ;
use MyUtils;
use MyGeom;
use PDB;
use ConfigPDB;
use Math::Geometry ;
use Math::Geometry::Planar;


use Time::HiRes qw( usleep ualarm gettimeofday tv_interval clock_gettime clock_getres  clock);
use POSIX qw(floor);
my $commandline = util_get_cmdline("",\@ARGV) ;
my ($infile,$p1,$p2,$outfile,$cutoff,$which_tech,$listfile,$protein);
my ($ignorefile,@expressions);
my $howmany = 100000 ;
my $idx = 0;
my $verbose = 1 ;
GetOptions(
            "which_tech=s"=>\$which_tech ,
            "protein=s"=>\$protein ,
            "infile=s"=>\$infile ,
            "p1=s"=>\$p1 ,
            "p2=s"=>\$p2 ,
            "listfile=s"=>\$listfile ,
            "ignorefile=s"=>\$ignorefile ,
            "outfile=s"=>\$outfile ,
            "expr=s"=>\@expressions,
            "idx=i"=>\$idx ,
            "verbose=i"=>\$verbose ,
            "cutoff=f"=>\$cutoff ,
           );
die "Dont recognize command line arg @ARGV " if(@ARGV ne 1);

$infile = $ARGV[0];
my $ifh = util_read($infile);
my $info = {};
my $ORIGCNT = 0 ;
while(<$ifh>){
     next if(/^\s*$/);
	 next if(/^\s*#/);

     chomp ;
	 my (@l) = split ;
	 my $nm = $l[$idx];


	 $info->{$nm} = 0 if(!defined $info->{$nm});
	 $info->{$nm} =$info->{$nm} + 1;
	 $ORIGCNT++;
}
close($ifh);

my $ofh = util_write("$infile.uniq");
my $ofhmult = util_write("$infile.mult");
my $CNT = 0;
foreach my $k (sort keys %{$info}){
     #$k = uc($k);
	 my $val = $info->{$k} ; 
	 if(!defined $val){
	 	 die " how is this happeing $k \n";
	 }
	 if($val > 1){
	 	print $ofhmult "$k $val\n";
	 }
	 print $ofh "$k\n";
	 $CNT++;
}
print "Uniq for $infile, started with $ORIGCNT ended with $CNT\n";



sub usage{
    my ($msg) = @_ ;
    print $msg , "\n" ; 
print << "ENDOFUSAGE" ; 
ENDOFUSAGE
    die ;
}
